apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project to group the teams applications and provide overall access to the Cluster, to the Platform Team.

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - "*" ##Lock down

  # Only permit applications to deploy to the 'guestbook' namespace or any namespace starting with 'guestbook-' in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  # Destinations also allow wildcard globbing
  - namespace: "*" #Platform are admins
    server: https://kubernetes.default.svc
    name: in-cluster

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - my-oidc-group

  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system
  - name: ci-role
    description: Sync privileges for guestbook-dev
    policies:
    - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow

  # # Sync windows restrict when Applications may be synced. https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
  # syncWindows:
  # - kind: allow
  #   schedule: '10 * * * *'
  #   duration: 1h
  #   applications:
  #     - '*-prod'
  #   manualSync: true
  # - kind: allow
  #   schedule: '0 9 * * *'
  #   duration: 8h
  #   applications:
  #     - '*'
  #   syncOverrun: true  # Syncs started during this window can continue after window ends
  # - kind: deny
  #   schedule: '0 22 * * *'
  #   duration: 1h
  #   namespaces:
  #     - default
  #   syncOverrun: true  # Syncs started before this window can continue during the window
  # - kind: allow
  #   schedule: '0 23 * * *'
  #   duration: 1h
  #   clusters:
  #     - in-cluster
  #     - cluster1

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: true

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  sourceNamespaces:
    - "frontend-*"
    - "backend-*"
    - "data-*"
    - "platform-*"

  # # Source Integrity declares criteria for application source repositories, such as cryptographic signing, etc.
  # # https://argo-cd.readthedocs.io/en/latest/user-guide/source-integrity/
  # sourceIntegrity:
  #   git:
  #     policies:
  #       - repos:
  #           - url: 'https://github.com/foo/*'
  #           - url: '!https://github.com/foo/bar.git'
  #         gpg:
  #           mode: strict
  #           keys:
  #             - "D56C4FCA57A46444"