apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.publicALBGateway.name }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  controllerName: {{ .Values.publicALBGateway.controllerName }}