team: platform
environment: prod
labels:
  app: platform
  component: secrets
  env: prod
  team: platform
aws:
  accountId: "632988741882"
  region: us-east-1
clusterSecretStore_secrets_manager:
  role: eso_operator-irsa-role
  service: SecretsManager
  serviceAccountRef:
    name: external-secrets-sa
clusterSecretStore_parameter_store:
  role: eso_operator-irsa-role
  service: ParameterStore
  serviceAccountRef:
    name: external-secrets-sa