apiVersion: argoproj.io/v1alpha1 ##whole template needs to be parameterised
kind: Application
metadata:
  name: gateway-api-crds
  namespace: platform-prod
spec:
  project: platform-team
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: release-1.6
    path: config/crd

  destination:
    server: "https://kubernetes.default.svc" ##Check
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    # syncOptions:
    #   - ServerSideApply=true # Recommended for large CRD manifests