app:
  Name: "redis-operator"
thirdParty:
  repoURL: "https://github.com/OT-CONTAINER-KIT/redis-operator.git"
  targetRevision: "v0.26.0"
  path: "charts/redis-operator"
valuesRepoURL: https://github.com/grayburnd/private-gitops-values.git
prune: true
selfHeal: true
ignoreDifferences: []
  
