apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.environment }}-cluster-secret-store-parameter-store
  annotations:
    external-secrets.io/ignore-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore_parameter_store.service }}
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore_parameter_store.serviceAccountRef.name }}
            namespace: {{ .Values.team }}-{{ .Values.environment }}
