app:
  Name: "karpenter"
thirdParty:
  repoURL: "https://github.com/aws/karpenter-provider-aws.git"
  targetRevision: "v1.14.1"
  path: "charts/karpenter"
valuesRepoURL: https://github.com/grayburnd/private-gitops-config.git
prune: true
selfHeal: true
ignoreDifferences: []
  
