app:
  Name: "gateway-api-crds"
thirdParty:
  repoURL: "https://github.com/kubernetes-sigs/gateway-api"
  targetRevision: "release-1.6"  
  path: "config/crd"
prune: true
selfHeal: true
ignoreDifferences: []
  
