app:
  Name: "external-secrets"
thirdParty:
  repoURL: "https://github.com/external-secrets/external-secrets.git"
  targetRevision: "helm-chart-2.9.0"
  path: "deploy/charts/external-secrets"
repoURL: https://github.com/grayburnd/platform-gitops.git
prune: true
selfHeal: true
ignoreDifferences: []
  
