apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-third-party-crds
  namespace: kube-system ##Only for Prod
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix: #Used to create seperate env for every app folder detected
        generators:
          - git:
              repoURL: https://github.com/grayburnd/platform-gitops.git
              revision: HEAD
              files:
                - path: crds/*/prod-config.yml
          - list:
              elements:
                - env: prod
                  team: platform
                  cluster: https://kubernetes.default.svc
  template:      
    metadata:
      name: '{{ .app.Name }}-{{ .env }}'
    spec:
      # The project the application belongs to.
      project: '{{ .team }}'
      # Source of the application manifests
      source:
        repoURL: '{{ .thirdParty.repoURL }}'
        path: '{{ .thirdParty.path }}'
        targetRevision: '{{ .thirdParty.targetRevision }}' ##Check
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{ .cluster }}'
        namespace: 'kube-system'
      # Sync policy
      syncPolicy:
        syncOptions:
          - ServerSideApply=true ##Useful for large resources i.e CRDs
          - ApplyOutOfSyncOnly=true  
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
      