name: CI [Lint]

on:
  pull_request:
permissions:
  contents: read
  pull-requests: read ##GitLeaks required.
# env:
#   TARGET_LINT_DIRECTORIES: "'apps' 'bootstrap'" ##Needs to be a Bash List type. See https://stackoverflow.com/questions/44164017/assigning-a-bash-variable-to-be-a-list-of-two-word-strings
jobs:
  ci-lint-and-checks:
    environment:
      name: prod
      deployment: false
    runs-on: ubuntu-latest
    steps:

      - name: Checkout local Git Repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          # required
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout Helm values repo
        uses: actions/checkout@v7.0.1
        with:
          repository: grayburnd/private-gitops-values
          token: ${{ steps.app-token.outputs.token }}
          ref: 'main'
          path: values

      - name: Install kubetools
        uses: yokawasa/action-setup-kube-tools@v0.13.5

      - uses: gitleaks/gitleaks-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm lint all k8s manifests
        run: |
          set -e -E -u -o pipefail
          for dir in ${{ vars.TARGET_LINT_DIRECTORIES }}; do
            original_dir=$(pwd)
            echo "===VALIDATING K8S $dir MANIFESTS==="
            for app in $(ls ${dir}/); do
              cd ${dir}/${app}
              helm lint -f=../../values/${{ vars.TEAM }}-gitops/${dir}/${app}/${{ vars.ENVIRONMENT }}-values.yml . &
              wait $!
              cd ${original_dir};
            done;
          done;
    
#We use -ignore-missing-schemas to exclude custom CRDs for simplicity/demo purposes
#We use -strict to disallow additional properties not in schema or duplicated keys
      - name: Kubeconform validate all app manifests
        run: |
          set -e -E -u -o pipefail
          for dir in ${{ vars.TARGET_LINT_DIRECTORIES }}; do
            original_dir=$(pwd)
            echo "===VALIDATING K8S $dir MANIFESTS==="
            for app in $(ls ${dir}/); do
              cd ${dir}/${app}
              helm template . -f=../../values/${{ vars.TEAM }}-gitops/${dir}/${app}/${{ vars.ENVIRONMENT }}-values.yml | kubeconform -ignore-missing-schemas -strict &
              wait $!
              cd ${original_dir};
            done;
          done;
