app:
  Name: "kube-prometheus-stack"
thirdParty:
  repoURL: "https://github.com/prometheus-community/helm-charts.git"
  targetRevision: "alertmanager-snmp-notifier-2.1.1"
  path: "charts/kube-prometheus-stack"
valuesRepoURL: https://github.com/grayburnd/private-gitops-config.git
prune: true
selfHeal: true
ignoreDifferences: []
  
